---
- name: "installation de php"
  apt:
    name:
      - php7.1-common
      - php7.1-cli
      - php7.1-common
      - php7.1-cli
      - php7.1-dev
      - php7.1-gd
      - php7.1-curl
      - php7.1-json
      - php7.1-opcache
      - php7.1-xml
      - php7.1-mbstring
      - php7.1-pdo
      - php7.1-mysql
      - php-apcu
    state: present
- name: "vérification installation php"
  debug:
    msg: "php is OK"
